### ISSUE TITLE
Feature Request - Buttons control system volume when Player is set to fixed Volume

### ISSUE THREAD

**Issue by cirdanlunae** [CDrummond/lms-material-app#13]
Situation where this would be useful: Using Squeezelite on Android and having Volume set to 100% fixed. While in LMS App, if player is Fixed, volume buttons on phone bypass the app and control system volume, so Volume for music can be set without leaving the app. This would better emulate a local player app.

**Comment by CDrummond** [comment]
This app simply forwards volume up/down keys onto main MaterialSkin Javascript WebApp.

Are you stating that you want this app to **not** forward the volume key presses on, but have them forwarded to Android itself? Sorry, but that is not (easily) doable. This app is a simple WebVie wrapper, it does not store state of current player and does not know if current player is fixed volume.

Even if it did, this would then lead to an inconsistency - where hardware volume buttons work this way, but the rest of Material's controls do not.

**Comment by CDrummond** [comment]
Closing. No updates, and feature would lead to inconsistency.

**Comment by eengnr** [comment]
Hi, I just wanted to ask the same and saw that this feature request already existed.

Would it perhaps be possible to make this optional? I.e. to add a switch to the settings to enable/disable to forward the volume controls to Android instead of the WebApp?

Just like the OP I'm also using a fixed 100% volume for my Android device to avoid changing the player volume in Squeeze Ctrl. With a fixed volume, Squeeze Ctrl changes the Android system volume instead of the player volume.

It would be nice to have this in your LMS App as well, then I could switch over to your app from Squeeze Ctrl.
Currently it's confusing, because as long as your app is in the foreground, I can only control the player volume (and have to disable its fixed volume for this), but when I leave your app, I control the Android volume instead.

**Comment by vext01** [comment]
Same here.

I installed the app on my DAP, and the volume wheel is hijacked by the app for the software volume of the (locally running) squeezelite. I'd prefer it to adjust the system volume.

Great app by the way. Many thanks.
